/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulario;

import Formulario.Consultas.form_consultas;
import Formulario.Inventario.form_alta_inv;
import Formulario.Inventario.form_baja_inv;
import Formulario.Inventario.reportes_inv;
import Formulario.Nominas.form_nominas;
import Formulario.Personal.form_alta_personal;
import Formulario.Personal.form_baja_personal;

/**
 *
 * @author flori
 */
public class menu_principal extends javax.swing.JFrame {

    /**
     * Creates new form menu_principal
     */
    public menu_principal() {
        initComponents(); 
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        escritorio = new javax.swing.JPanel();
        escritorio1 = new javax.swing.JDesktopPane();
        nominas = new javax.swing.JButton();
        personal = new javax.swing.JButton();
        inventario = new javax.swing.JButton();
        MenuPrincipal = new javax.swing.JMenuBar();
        Inventario = new javax.swing.JMenu();
        inv_altas = new javax.swing.JMenuItem();
        inv_bajas = new javax.swing.JMenuItem();
        inv_reportes = new javax.swing.JMenuItem();
        Personal = new javax.swing.JMenu();
        altas = new javax.swing.JMenuItem();
        bajas = new javax.swing.JMenuItem();
        Nominas = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        Consultas = new javax.swing.JMenu();
        con_altas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setForeground(new java.awt.Color(0, 51, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(966, 600));

        escritorio1.setBackground(new java.awt.Color(0, 51, 153));

        nominas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nominas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inventario.png"))); // NOI18N
        nominas.setText("Inventario");
        nominas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nominas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        nominas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nominas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nominasActionPerformed(evt);
            }
        });

        personal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        personal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Personal.png"))); // NOI18N
        personal.setText("Personal");
        personal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        personal.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        personal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        personal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalActionPerformed(evt);
            }
        });

        inventario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nominas.png"))); // NOI18N
        inventario.setText("Nominas");
        inventario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inventario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        inventario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioActionPerformed(evt);
            }
        });

        escritorio1.setLayer(nominas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio1.setLayer(personal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio1.setLayer(inventario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorio1Layout = new javax.swing.GroupLayout(escritorio1);
        escritorio1.setLayout(escritorio1Layout);
        escritorio1Layout.setHorizontalGroup(
            escritorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorio1Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(nominas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(77, 77, 77)
                .addComponent(personal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(86, 86, 86)
                .addComponent(inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(162, 162, 162))
        );
        escritorio1Layout.setVerticalGroup(
            escritorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorio1Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(escritorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nominas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(212, 212, 212))
        );

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(escritorio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 212, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio1)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MenuPrincipal.setForeground(new java.awt.Color(0, 51, 153));

        Inventario.setText("Inventario");

        inv_altas.setText("Altas");
        inv_altas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inv_altasActionPerformed(evt);
            }
        });
        Inventario.add(inv_altas);

        inv_bajas.setText("Bajas");
        inv_bajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inv_bajasActionPerformed(evt);
            }
        });
        Inventario.add(inv_bajas);

        inv_reportes.setText("Reportes");
        inv_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inv_reportesActionPerformed(evt);
            }
        });
        Inventario.add(inv_reportes);

        MenuPrincipal.add(Inventario);

        Personal.setText("Personal");
        Personal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonalActionPerformed(evt);
            }
        });

        altas.setText("Altas");
        altas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altasActionPerformed(evt);
            }
        });
        Personal.add(altas);

        bajas.setText("Bajas");
        bajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajasActionPerformed(evt);
            }
        });
        Personal.add(bajas);

        MenuPrincipal.add(Personal);

        Nominas.setText("Nominas");

        jMenuItem1.setText("Altas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Nominas.add(jMenuItem1);

        MenuPrincipal.add(Nominas);

        Consultas.setText("Consultas");

        con_altas.setText("Altas");
        con_altas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_altasActionPerformed(evt);
            }
        });
        Consultas.add(con_altas);

        MenuPrincipal.add(Consultas);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altasActionPerformed
        // TODO add your handling code here:
        form_alta_personal p1 = new form_alta_personal();
        escritorio1.add(p1);
        p1.show();
        
        
    }//GEN-LAST:event_altasActionPerformed

    private void PersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PersonalActionPerformed

    private void inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioActionPerformed
        // TODO add your handling code here:
        form_nominas p1 = new form_nominas();
        escritorio1.add(p1);
        p1.show();
    }//GEN-LAST:event_inventarioActionPerformed

    private void nominasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nominasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nominasActionPerformed

    private void personalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personalActionPerformed

    private void bajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajasActionPerformed
        // TODO add your handling code here:
        form_baja_personal p1 = new form_baja_personal();
        escritorio1.add(p1);
        p1.show();
    }//GEN-LAST:event_bajasActionPerformed

    private void inv_bajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inv_bajasActionPerformed
        // TODO add your handling code here:
        form_baja_inv p1 = new form_baja_inv();
        escritorio1.add(p1);
        p1.show();
    }//GEN-LAST:event_inv_bajasActionPerformed

    private void inv_altasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inv_altasActionPerformed
        // TODO add your handling code here:
        form_alta_inv p1 = new form_alta_inv();
        escritorio1.add(p1);
        p1.show();
    }//GEN-LAST:event_inv_altasActionPerformed

    private void inv_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inv_reportesActionPerformed
        // TODO add your handling code here:
        reportes_inv p1 = new reportes_inv();
        escritorio1.add(p1);
        p1.show();
    }//GEN-LAST:event_inv_reportesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        form_nominas p1 = new form_nominas();
        escritorio1.add(p1);
        p1.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void con_altasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_altasActionPerformed
        // TODO add your handling code here:
        form_consultas p1 = new form_consultas();
        escritorio1.add(p1);
        p1.show();
               
    }//GEN-LAST:event_con_altasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Consultas;
    private javax.swing.JMenu Inventario;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenu Nominas;
    private javax.swing.JMenu Personal;
    private javax.swing.JMenuItem altas;
    private javax.swing.JMenuItem bajas;
    private javax.swing.JMenuItem con_altas;
    private javax.swing.JPanel escritorio;
    private javax.swing.JDesktopPane escritorio1;
    private javax.swing.JMenuItem inv_altas;
    private javax.swing.JMenuItem inv_bajas;
    private javax.swing.JMenuItem inv_reportes;
    private javax.swing.JButton inventario;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nominas;
    private javax.swing.JButton personal;
    // End of variables declaration//GEN-END:variables
}
